### ISSUE TITLE
[CT-1843] [Feature] Generic `tmp_relation_type` config for incremental models

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-snowflake#402]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

https://github.com/dbt-labs/dbt-snowflake/pull/389 was merged, which adds the `merge_tmp_relation_type` configuration that only applies to the `merge` strategy.

So we'll probably want to make a decision on the following proposal (from [here](https://github.com/dbt-labs/dbt-snowflake/issues/323#issuecomment-1382015544)) before the RC2 that includes that feature is released.

---

As @McKnight-42 and I iterated on the implementation of https://github.com/dbt-labs/dbt-snowflake/issues/323, a question came up how we should handle the `merge_tmp_relation_type` config for strategies other than the `default` strategy of `merge`.

Consider the `append` strategy:
- How _should_ it behave if the user specifies `merge_tmp_relation_type=table` and `strategy=append`?
    - we currently would use a temporary `view`

### Three options
We have three main options:
1. Raise an exception that the `merge_tmp_relation_type` configuration doesn't apply to this strategy
1. (Silently?) ignore the `merge_tmp_relation_type` configuration 
1. Expand the scope so that a `incremental_tmp_relation_type` config also applies to the rest of the incremental strategies (but only when provided)

### Trade-offs
Primary trade-off of each option (in corresponding order):
1. Could be frustrating to the user if they can control the type of temporary object for only the `merge` strategy but not the others.
1. Could be confusing if they specify `table` but it uses a `view` anyways.
1. A user could override to use a temporary object in a way that is less efficient than the alternative. (i.e., configuring `table` in a case where `view` would have been faster.) Also, the discerning eye will see that that `language!=sql` will still use `table` no matter what the user says.

### Proposal
So I'd like to propose that we actually do the third option! This would expand the scope slightly to cover other incremental strategies also.

One advantage is that writing the documentation for the third option would be the most simple. It would also be easiest to understand from a user perspective:
- when this option is provided (for SQL models), then the adapter will do whatever you say
- otherwise, then the adapter will do whatever it thinks best

### Trying on Option Three

Suppose the new config name is `tmp_relation_type`. Then the pseudo logic would be:

```
if language == "sql" and tmp_relation_type == "table":
    return "table"
else if language == "sql" and tmp_relation_type == "view":
    return "view"
else:
    return whatever the current logic returns
```

> As a user, I prefer the name `tmp_relation_type` over `incremental_tmp_relation_type` since it is shorter and not redundant with the materialization type of `incremental`)

Expanding this out to include all the current logic (and simplifying the `language` a teensy bit):
```
if language == "python":
    return "table"
else if tmp_relation_type == "table":
    return "table"
else if tmp_relation_type == "view":
    return "view"
else if strategy in ('default', 'merge', 'append'):
    return "view"
else if unique_key is none:
    return "view"
else:
    return "table"
```

> Note that `delete+insert` is the only strategy not explicitly referenced by name and it will use `view` unless a `unique_key` is provided.

### Current Logic in PR [#389](https://github.com/dbt-labs/dbt-snowflake/pull/389)

If we keep the original decision to have a `merge_tmp_relation_type` config that only applies to the `merge` strategy, then the logic could be essentially like:
```
# TODO:
# Either raise an error if `merge_tmp_relation_type` is configured for a strategy other than `default` or `merge`
# or ignore altogether

if language == "python":
    return "table"
else if strategy in ('default', 'merge') and merge_tmp_relation_type == "table":
    return "table"
else if strategy in ('default', 'merge') and merge_tmp_relation_type == "view":
    return "view"
else if strategy in ('default', 'merge', 'append'):
    return "view"
else if unique_key is none:
    return "view"
else:
    return "table"
```

Ultimately, the two variations aren't that substantially different from each other. However, if we do ever want to come back and allow strategies other than `merge` to configure their temp object type, then the implementation in code will get uglier, and the documentation will be more complicated.

If we allow all incremental strategies to provide this config in one fell swoop right now, then we'll complete the offering of a  balance of rational defaults along with configurability for intermediate temp objects used by incremental models.

### Describe alternatives you've considered

See above.

The main alternative is a `merge_tmp_relation_type` config that is meant to only ever apply to the `merge` strategy and never apply to any other incremental strategy.

### Who will this benefit?

If we ever foresee being able to configure the temporary object type (table vs. view) for an incremental strategy other than `merge`, it would be better to do this now rather than later.

### Are you interested in contributing this feature?

Happy to help however

**Comment by jtcohen6** [comment]
Thanks for working toward + writing up this detailed proposal @dbeatty10 @McKnight-42!

I agree with your instincts toward Option 3:

> Expand the scope so that a `incremental_tmp_relation_type` config also applies to the rest of the incremental strategies (but only when provided)

Let's make it so!

As a UX note, if the user has configured something that is actively disallowed, I think we should raise a clear exception, rather than raising a warning and implicitly using the non-configured behavior anyway. So we should raise an exception in cases where:
- `languge == 'python' and incremental_tmp_relation_type == 'view'` (although, Snowpark in particular might be able to support views someday)
- `incremental_strategy == 'delete+insert' and incremental_tmp_relation_type == 'table'` (risk of inconsistent results between `delete` + `insert`)

Let's just make sure that, in making this change, we're also updating this code comment! In this case, given the underlying complexity, verbose is good.
https://github.com/dbt-labs/dbt-snowflake/blob/45948bdf440500a99eb9628fd01ddb4c3df38d43/dbt/include/snowflake/macros/materializations/incremental.sql#L4-L20

**Comment by dbeatty10** [comment]
@jtcohen6 or @Fleid:
- is there a reason we should have a `incremental_` prefix for the `tmp_relation_type` config?
- and are you opposed to using `tmp_relation_type` rather than `incremental_tmp_relation_type`?

As a user, I prefer the name `tmp_relation_type` over `incremental_tmp_relation_type` since it is shorter. Another reason is that it is not redundant with the materialization type of `incremental`.

e.g., All things being equal, I'd rather this configuration:
```sql
{{
  config(
    materialized="incremental",
    incremental_strategy="merge",
    tmp_relation_type="table",
    ...
  )
}}
```

as opposed to:
```sql
{{
  config(
    materialized="incremental",
    incremental_strategy="merge",
    incremental_tmp_relation_type="table",
    ...
  )
}}
```

But you might know reason(s) why having an `incremental_` prefix is superior.

**Comment by McKnight-42** [comment]
@jtcohen6 would this be a warning more than a full exception?

> incremental_strategy == 'delete+insert' and incremental_tmp_relation_type == 'table' (risk of inconsistent results between delete + insert)

my understanding is that if we are doing multiple statements for `delete+insert` then indeed we use temp tables because deletes will happen

but that during a single run where nothing is deleted a temp view is faster?

or is this only a exception in the case that `unique_key` is `None`

**Comment by dbeatty10** [comment]
@McKnight-42 Yep, that sounds about right to me.

I think it would only be an exception in this case:
```
if incremental_strategy == 'delete+insert' and unique_key is not none and tmp_relation_type != 'table'
```

Of course before doing a check like the above, we'd want to make sure that `tmp_relation_type` is defined (i.e. not `none`).
