### ISSUE TITLE
[ADAP-526] [Spike] Macro for warehouse selection

### ISSUE THREAD

**Issue by Fleid** [dbt-labs/dbt-snowflake#599]
# Spike
Timeboxed investigation to see what can be done about https://github.com/dbt-labs/dbt-snowflake/issues/103

## To-do:
- [ ] Read through the thread and understand the requirement
- [ ] See the proposed [implementation](https://github.com/dbt-labs/dbt-snowflake/pull/115) and the associated [bug](https://github.com/dbt-labs/dbt-snowflake/issues/533)
- [ ] See the alternative approach proposed [internally](https://github.com/dbt-labs/internal-analytics/pull/1559) - I don't see this as a viable approach, but it shines a light on the bug above

## Outcome:
- A simple explanation of what is going on
- Options to move forward with an estimated complexity

**Comment by epapineau** [comment]
@Fleid is there any update here? 🙏🏻

**Comment by manugarri** [comment]
@Fleid would love to hear how its going :)
